### ISSUE TITLE
App class related to a DaggerMainComponent class but there is no such thing

### ISSUE THREAD

**Issue by nikunjdaga** [ahmedeltaher/MVP-RX-Android-Sample#1]
Code is showing errors

**Comment by ahmedeltaher** [comment]
it is Dagger generated class for MainComponent interface . 
it is not issue . 
please check dagger wiki page `Instantiating the component` 
`https://github.com/codepath/android_guides/wiki/Dependency-Injection-with-Dagger-2`
I think you need to clean and build it again
